title:
  de: Standardseite
  en: Default Page

tabs:
  # Tab: Content
  t_content:
    label:
      de: Inhalt
      en: Content
    columns:
      - width: 2/3
        sections:
          s_content:
            type: fields
            fields:
              text:
                label: Text
                type: blocks

      - width: 1/3
        sections:
          s_files:
            headline:
              de: Dateien
              en: Files
            type: files


  # Tab: SEO
  t_seo: seo
