title: Default Page
tabs:
  content:
    icon: page
    columns:
      content:
        width: 2/3
        fields:
          text:
            label: Text
            type: editor
      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
          files:
            type: files

  seo:
    icon: search
    columns:
      content:
        width: 2/3
        fields:
          seo: fields/seo
      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
          files:
            type: files
