title: Site

tabs:
  pages:
    icon: page
    sections:
      pages:
        type: pages

  seo:
    icon: search
    columns:
      content:
        width: 2/3
        fields:
          seo_description:
            label: Fallback Description
            type: textarea
            buttons: false
            maxlength: 160
            width: 2/3
            size: medium
            help: Search engines might use this description
          seo_image:
            label: Fallback Image
            type: files
            multiple: false
            layout: cards
            width: 1/3
            help: This may be used as a preview for your page/site
            image:
              ratio: 1/1

      sidebar:
        width: 1/3
        sections:
          files:
            type: files
          structuredinfo:
            type: info
            headline: Structured Data
            text: >
              After saving, use the (link: https://search.google.com/structured-data/testing-tool#url={{ site.url }} text: Google Structured Data Testing Tool) to verify the schema.
