title: Site

tabs:
  pages:
    icon: page
    label:
      de: Seiten
      en: Pages
    columns:
      - width: 2/3
        sections:
          s_pages:
            type: pages
            headline:
              de: Seiten
              en: Pages
            image: icon
            templates:
              - home
              - default

      - width: 1/3
        sections:
          s_collections:
            type: pages
            headline:
              de: Sammlungen
              en: Collections
            image: icon
            templates:
              - authors

  # Tab: Settings
  settings:
    icon: settings
    label:
      de: Einstellungen
      en: Settings
    fields:
      # Social Media
      h_social:
        type: headline
        label: Social Media
        numbered: false
      social_url_twitter:
        label: Twitter
        type: url
        icon: twitter
        width: 1/3
      social_url_facebook:
        label: Facebook
        type: url
        icon: facebook
        width: 1/3
      social_url_instagram:
        label: Instagram
        type: url
        icon: instagram
        width: 1/3

  # Tab: SEO
  t_seo: seo
